config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"
  resources :recipes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users do
    get :follow, on: :member
    get :follower, on: :member
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :content, presence: true
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  attachment :image

  has_many :likes, dependent: :destroy

  has_many :comments, dependent: :destroy 

  validates :title, presence: true, length: {maximum: 50 }
  validates :body, presence: true, length: { maximum: 255 }
  validates :image_id, presence: true
  
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :username, presence: true, uniqueness:true, length: {in: 2..20}
  validates :profile, length: { maximum: 50}

  has_many :recipes, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得

  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  has_many :comments, dependent: :destroy
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(resource) # ログイン後に遷移するpathを設定
  end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  # before_action :correct_user, only: [:destroy]
  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    Comment.find_by(id: params[:id],recipe_id: params[:recipe_id]).destroy
    redirect_to recipe_path(@recipe)
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :recipe_id)  #formにてpost_idパラメータを送信して、コメントへpost_idを格納するようにする必要がある。
  end
  # def correct_user
  #   comment = current_user.comments.find_by(id: params[:id])
  #   unless comment
  #     redirect_to root_url
  #   end
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_recipe, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, recipe_id: params[:recipe_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, recipe_id: params[:recipe_id])
    like.destroy
  end

  private
  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_recipe, only: %i(show edit update destroy)

  def index
    @recipes = Recipe.all.order(id: "DESC")
  end

  def show
    @comments = @recipe.comments
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe), notice: "レシピを投稿しました。"
    else
      render :new
    end
  end
  

  def edit
    if @recipe.user != current_user
        redirect_to recipes_path, alert: "不正なアクセスです。"
    end
  end
  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: "レシピを更新しました。"
    else
      render :edit
    end
  end
  
  def destroy
    @recipe.destroy
    redirect_to user_path(current_user), notice: "レシピを削除しました。"
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :body, :image, :comment)
  end

  def set_recipe
    @recipe = Recipe.find_by(id: params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def follow
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end
  
  def unfollow
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, only: %i(show edit update destroy follow follower)

  def follow
    @users = @user.follower
  end
  
  def follower
    @users = @user.followed
  end
  
  def index
    @users = User.all
  end

  def show
  end

  def edit
    if @user != current_user
        redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
  end

  private
  def user_params #ストロングパラメーター
    params.require(:user).permit(:username, :email, :profile, :profile_image) #許可されているキー
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
  <%= form_with(model:[recipe, comment], method: :post) do |f|%>
    <%= f.text_field :content %>
    <%= f.hidden_field :recipe_id, value: recipe.id%>
    <%= f.submit 'コメントする' %>
  <% end %>

app/views/comments/create.js.erb
$("#comments_area_<%= @recipe.id %>").html("<%= j(render "recipes/comment", comment: @comments) %>")
$("textarea").val('')

app/views/comments/destroy.js.erb
$("#comments_area_<%= @recipe.id %>").html("<%= j(render "recipes/comment", comment: @comment) %>")

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">Cookingram</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
        <% if user_signed_in? %>
        
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        <% end %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
  <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class:"navber-item" do  %>
        <h1 class="title is-4" style="font-family: cursive;">Cookingram</h1>
      <% end %> 
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", recipes_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "レシピ投稿", new_recipe_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "レシピグラマー一覧", users_path, class: " button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-item">
        <%= link_to "レシピ一覧", recipes_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-item">
        <%= link_to "レシピグラマー一覧", users_path, class: "navbar-item button is-warning is-light" %>
      </div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookingran</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  </head>

  <body>
  <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% unless recipe.like_user(current_user.id).blank? %>
    <%= link_to recipe_like_path(recipe_id: recipe.id, id: recipe.likes[0].id), method: :delete, remote: true do %>
      <td class="vertical_like">
        <%= image_tag "red_heart.png", size: '40x40' %>
      </td>
    <% end %>
  <% else %>
    <%= link_to recipe_likes_path(recipe.id), method: :post, remote: true do %>
      <td class="vertical_like">
        <%= image_tag "white_heart.png", size: '40x40' %>
      </td>
    <% end %>
  <% end %>
      <td><%= recipe.likes.count %></td>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons<%= @recipe.id %>').html("<%= j(render partial: 'likes/like', locals: {recipe: @recipe,like: @like}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons<%= @recipe.id %>').html("<%= j(render partial: 'likes/like', locals: {recipe: @recipe, like: @like}) %>");

app/views/recipes/_comment.html.erb
<table class="table">
  <thead>
      <th>コメント投稿者</th>
        <th>コメント内容</th>
          <th colspan="2"></th>
            <% @recipe.comments.each do |comment| %>
            <tr>
              <td><%= link_to user_path(comment.user) do %>
                <%= attachment_image_tag comment.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %><br>
                <%= comment.user.username  %>
              <% end %>
              </td>
              <td><%= comment.content %></td>
                <td><% if comment.user_id == current_user.id %>
                  <%= link_to "Destroy", recipe_comment_path(comment.recipe.id, comment.id), class: 'btn-sm btn-danger',method: :delete, remote: true %>
                  <% end %>
                </td>
              <td class="comment-date pull-right">
                <%= comment.created_at.strftime('%Y/%m/%d') %>
              </td>
              </tr>
            <% end %>
          </table>
        </div>
      </tr>
    </thead>
  </tbody>
</table>

app/views/recipes/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model:@recipe, local:true do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class:"label" %>
            <%= f.text_field :title, class:"input" %>
            </div>

            <div class="field">
            <%= f.label :body, "作り方", class:"label" %>
            <%= f.text_area :body, class:"textarea" %>
            </div>

            <div class="field">
            <%= f.label :image, "写真", class:"label" %>
            <%= f.attachment_field :image, class:"input" %>
            </div>

            <%= f.submit "更新", class:"button is-success" %>
            <% end %>
          </div>
        </div>
      </div>
    </section>

app/views/recipes/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>   <%# 一覧を表示する場合はeach文を使い一つ一つ取り出す %>
      <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
              <%= link_to recipe_path(recipe) do %>  <%#引数にどのレシピに行くかいれる%>
                <%= attachment_image_tag recipe, :image %>
                <% end %>
                </figure>
            </div>
                          <%# いいね表示 %>
              <div id="likes_buttons<%= recipe.id %>">
                <%= render partial: 'likes/like', locals: { recipe: recipe, like: @like} %>
              </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                  <%= link_to user_path(recipe.user.id) do %>
                  <%= attachment_image_tag recipe.user, :profile_image, fallback: "no_image.jpg" %>
                  <% end %>
                  </figure>
                </div>
                <div class="media-content"><%# レシピに紐づいているユーザーにいくようなパス%>
                  <div class="title"><%= link_to recipe.user.username, user_path(recipe.user) %></div>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規レシピ作成
      </h1>
    </div>
  </div>
</section>


<% if @recipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @recipe, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @recipe.title %></p>
              </div>
              <%# いいね表示 %>
              <div id="likes_buttons<%= @recipe.id %>">
                <%= render partial: 'likes/like', locals: { recipe: @recipe, like: @like} %>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.body %></td>
                </tr>
              </table>
              <% if @recipe.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_recipe_path(@recipe), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-5">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @recipe.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @recipe.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@recipe.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @recipe.user.username %> さんのページへ
          <% end %>
        </article>
      <%# コメント機能 %>
      <h2>コメントする</h2>
        <%= render 'comments/form', recipe:@recipe, comment: @comment %>
      <h2>コメント一覧</h2>
      <div id="comments_area_<%= @recipe.id %>">
          <%= render partial: 'recipes/comment', local: {comment: @comment} %>
      </div>
      </div>


    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/follow.html.erb
<div class='col-md-10 offset-md-1'>
  <h3>Follow Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
          <% @user.following_user.where.not(id: current_user.id).each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
            <td><%= "#{user.username}" %></td>
            <td><%="フォロー中: #{user.follower.count}" %></td>
            <td><%= "フォロワー: #{user.followed.count}" %></td>
            <td><%= link_to "show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/follower.html.erb
<p id="notice"></p>
<div class='col-md'>
  <h3>Follower Users</h3>
    <% if @users.empty? %>
        <span>ユーザーはいません</span>
    <% else %>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th colspan="4"></th>
        </tr>
      </thead>
        <tbody>
          <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
            <tr>
            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg" , size:"40x40" %></td>
              <td><%= "#{user.username}" %></td>
              <td><%="フォロー中: #{user.follower.count}" %></td>
              <td><%= "フォロワー: #{user.followed.count}" %></td>
              <td><%= link_to "show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </tr>
  </table>
  <% end %>
</div>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピグラマー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.recipes.count %>
              </div>
                  <p>
                    <% unless current_user == user %>
                      <% if user_signed_in? %>
                        <% if current_user.following?(user) %>
                          <%= link_to 'フォロー中 ', unfollow_path(user.id), method: :POST %>
                        <% else %>
                          <%= link_to 'フォローする ', follow_path(user.id), method: :POST %>
                        <% end %>
                      <% end %>
                    <% end %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td> フォロー中: <%= link_to "#{@user.follower.count}", follow_user_path(@user.id) %></td>
                <td>フォロワー: <%= link_to "#{@user.followed.count}", follower_user_path(@user.id) %></td>
                  <% unless @user == current_user %>
                    <% if current_user.following?(@user) %>
                    <td>
                      <%= link_to 'フォロー中', unfollow_path(@user.id), method: :POST, class: 'btn btn-outline-primary' %>
                    </td>
                    <% else %>
                    <td>
                      <%= link_to 'フォローする', follow_path(@user.id), method: :POST, class: 'btn btn-outline-primary' %>
                    </td>
                    <% end %>
                  <% end %>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                  <%= attachment_image_tag recipe, :image, fallback: "no_image.jpg" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このレシピを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</section>